{
 "title": "API Metrics",
 "tags": [
  "metrics",
  "api",
  "prometheus"
 ],
 "time": { "from": "now-5m", "to": "now" },
 "panels": [
  {
   "title": "RPS API",
   "type": "timeseries",
   "description": "Количество запросов, которые система может обработать за 1 секунду",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "sum(rate(http_requests_total[1m]))"
    }
   ]
  },
  {
   "title": "P95 latency",
   "type": "timeseries",
   "description": "95-й перцентиль задержки HTTP-запросов",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(http_request_latency_seconds_bucket[5m])) by (le))"
    }
   ]
  },
  {
   "title": "Error rate",
   "type": "timeseries",
   "description": "Процент ошибок 5xx",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "sum(rate(http_requests_total{status=~\"5..\"}[5m])) / sum(rate(http_requests_total[5m]))"
    }
   ]
  }
 ]
}